### ISSUE TITLE
Anaplan connector project giving errors about missing artifact anaplan-connect-1.3.6.jar

### ISSUE THREAD

**Issue by nraghun** [anaplaninc/anaplan-mulesoft#73]
When I was trying to deploy an application which has Anaplan connector from Bamboo, it gives an error:
[INFO] Downloading: file:///opt/bamboo-agent/bamboo-agent-home/xml-data/build-dir/FS-ANAPLAN-ALLTESTS/src/main/resources/repo/com/anaplan/client/anaplan-connect/1.3.6/anaplan-connect-1.3.6.jar
build	28-Jul-2017 21:36:32	[INFO] ------------------------------------------------------------------------
build	28-Jul-2017 21:36:32	[INFO] BUILD FAILURE
build	28-Jul-2017 21:36:32	[INFO] ------------------------------------------------------------------------
build	28-Jul-2017 21:36:32	[INFO] Total time: 15.344 s
build	28-Jul-2017 21:36:32	[INFO] Finished at: 2017-07-28T21:36:32+00:00
build	28-Jul-2017 21:36:32	[INFO] Final Memory: 22M/495M
build	28-Jul-2017 21:36:32	[INFO] ------------------------------------------------------------------------
build	28-Jul-2017 21:36:32	[ERROR] Failed to execute goal on project atl_anaplan_app: Could not resolve dependencies for project com.atlassian.finsys:atl_anaplan_app:mule:1.0.0-SNAPSHOT: Could not find artifact com.anaplan.client:anaplan-connect:jar:1.3.6 in maven-atlassian-com (https://packages.buildeng.atlassian.com/maven/repository/internal) -> [Help 1]

In the project .classpath, 
<classpathentry kind="var" path="M2_REPO/com/anaplan/client/anaplan-connect/1.3.6/anaplan-connect-1.3.6.jar"/>
<classpathentry kind="var" path="M2_REPO/org/mule/modules/anaplan-connector/1.1.3/anaplan-connector-1.1.4.jar"/>

I tried removing the line with anaplan-connect-1.3.6.jar, but Maven adds it back when it cleans the project.

In pom.xml, the following lines are added:
<repositories>
<repository>
<id>mulesoft-releases</id>
<name>MuleSoft Releases Repository</name>
<url>http://repository.mulesoft.org/releases/</url>
<layout>default</layout>
</repository>
</repositories>
<pluginRepositories>
<pluginRepository>
<id>mulesoft-release</id>
<name>mulesoft release repository</name>
<layout>default</layout>
<url>http://repository.mulesoft.org/releases/</url>
<snapshots>
<enabled>false</enabled>
</snapshots>
</pluginRepository>
</pluginRepositories>

This jar is not present in the Mule repository.

**Comment by shuvozula** [comment]
Could you share some more details how you're using this connector? Are you building and using the connector in Anypoint Studio? How are you using Bamboo to build the connector?

From a clean build of the connector project (mvn clean install -U), I see it downloads the anaplan-connect:1.3.6 dependency properly and builds the project just fine.

**Comment by nraghun** [comment]
My local repository has the anaplan-connect-1.3.6.jar. When I am building the project in Anypoint Studio, it checks the local Maven repository and it is able to get the jar and build the project successfully. 

When building in Bamboo, the project checks the company's internal repo, which proxies the Mule repository. The following lines are added in pom.xml to proxy Mule repo, 
<repositories>
    <repository>
            <id>mulesoft-releases</id>
            <name>MuleSoft Releases Repository</name>
            <url>http://repository.mulesoft.org/releases/</url>
            <layout>default</layout>
        </repository>
</repositories>
<pluginRepositories>
        <pluginRepository>
            <id>mulesoft-release</id>
            <name>mulesoft release repository</name>
            <layout>default</layout>
            <url>http://repository.mulesoft.org/releases/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

In Mule repo, anaplan-connect-1.3.6.jar is not present, so it is not present in the company's internal repo. There the build fails.

**Comment by shuvozula** [comment]
I believe your problem is because of a missing repository definition in your pom.xml
```
        <repository>
            <id>anaplan-github-mvn-repo</id>
            <name>Anaplan Github MVN Repository</name>
            <url>https://raw.githubusercontent.com/anaplaninc/anaplaninc.github.io/mvn-repo-ac/</url>
            <layout>default</layout>
            <snapshots>
	            <enabled>true</enabled>
	            <updatePolicy>always</updatePolicy>
	        </snapshots>
        </repository>
```
Check this project's ```repositories``` in the pom.xml for details.

To test my theory:
If I remove my local Maven artifact for anaplan-connect from ~/.m2/repository/com/anaplan/client/anaplan-connect and build it again, the anaplan-connect jar is re-downloaded from anaplaninc.github.io, which is a publicly accessible Nexus.
```
Downloading: https://raw.githubusercontent.com/anaplaninc/anaplaninc.github.io/mvn-repo-ac/com/anaplan/client/anaplan-connect/1.3.6/anaplan-connect-1.3.6.jar
Downloaded: https://raw.githubusercontent.com/anaplaninc/anaplaninc.github.io/mvn-repo-ac/com/anaplan/client/anaplan-connect/1.3.6/anaplan-connect-1.3.6.jar (124 KB at 573.5 KB/sec)
```
So yes, Mulesoft is right, they don't control the dependencies for community connectors, as a result we hosted that dependency at anaplaninc.github.io.

In your case, you'd have to add the above ```repository``` definition to your pom to make it work.

Hope that helps!

**Comment by nraghun** [comment]
I tried the same way you mentioned, but I do not see it downloading from raw.githubusercontent.com/anaplaninc/

The below are the changes I made with your suggestion:

I compared this repo's pom.xml with mine and I added the following in pom.xml:
in `<dependencies>`
```
<dependency>
    <groupId>com.anaplan.client</groupId>
    <artifactId>anaplan-connect</artifactId>
    <version>1.3.6</version>
</dependency>
```

```
<repositories>
		<repository>
			<id>in-project</id>
			<name>In Project Repo</name>
			<url>file://${project.basedir}/src/main/resources/repo</url>
		</repository>	
        <repository>
            <id>Central</id>
            <name>Central</name>
            <url>http://repo1.maven.org/maven2/</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>mulesoft-releases</id>
            <name>MuleSoft Releases Repository</name>
            <url>http://repository.mulesoft.org/releases/</url>
            <layout>default</layout>
        </repository>
		<repository>
            <id>anaplan-github-mvn-repo</id>
            <name>Anaplan Github MVN Repository</name>
            <url>https://raw.githubusercontent.com/anaplaninc/anaplaninc.github.io/mvn-repo-ac/</url>
            <layout>default</layout>
            <snapshots>
	            <enabled>true</enabled>
	            <updatePolicy>always</updatePolicy>
	        </snapshots>
        </repository>
    </repositories>
<pluginRepositories>
        <pluginRepository>
            <id>mulesoft-release</id>
            <name>mulesoft release repository</name>
            <layout>default</layout>
            <url>http://repository.mulesoft.org/releases/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
    <distributionManagement>
        <repository>
            <id>atlassian-private</id>
            <name>Atlassian Private Repository</name>
            <url>https://maven.atlassian.com/private</url>
        </repository>
        <snapshotRepository>
            <id>atlassian-private-snapshot</id>
            <name>Atlassian Private Snapshot Repository</name>
            <url>https://maven.atlassian.com/private-snapshot</url>
        </snapshotRepository>
    </distributionManagement>
```

Then I removed Anaplan-connect folder from my local repo and I used `mvn clean package` in Terminal, but it gave errors:
<img width="1680" alt="screen shot 2017-08-01 at 5 32 24 pm" src="https://user-images.githubusercontent.com/11624269/28852687-f6bd9d82-76df-11e7-9727-c9008bcd201e.png">

I do not see the line about it downloading from Anaplan repo.

I tried adding the Anaplan repo under <pluginrepositories> also but that gave the same error.

**Comment by shuvozula** [comment]
In the pom.xml in this connector project, there's also a <url> field that seems to be required (https://github.com/anaplaninc/anaplan-mulesoft/blob/develop/pom.xml#L17). Try adding this to your pom.xml as well
```
<url>http://anaplaninc.github.io/mvn-repos</url>
```

There is also a <distributionManagement> section, but I don't think you need to add that since its only for pushing anaplan-mulesoft artifacts. But it doesn't hurt to also include and see if that makes a difference.

My hunch is the missing <url> will do the trick

**Comment by nraghun** [comment]
I had tried adding the repo in `<distributionManagement>`, but it gave an error because it already has the private repo there. I guess it can have only one `<repository>` tag.

I tried adding the <url>, but it still gives the same error.

I noticed that 
`Downloading: https://packages.atlassian.com/maven/repository/internal/com/anaplan/client/anaplan-connect/1.3.6/anaplan-connect-1.3.6.pom`
is occurring on the Terminal, the folder gets created, even though the link does not have that jar. 
It does not go to the Anaplan Repo link at all.

**Comment by shuvozula** [comment]
This seems like a problem with your approach of building the connector in Bamboo, where its unable to reach out to the github repos. From your earlier post, you mentioned that "When building in Bamboo, the project checks the company's internal repo, which proxies the Mule repository.". So you might have to add some exclusion rule in Bamboo to also add the https://raw.githubusercontent.com/anaplaninc/anaplaninc.github.io/mvn-repo-ac repo URL.

The link you posted above is only part of the URL, that maven uses and adds the classpath URL to it to fetch the artifacts, so obviously that will give a 404. The correct link is https://raw.githubusercontent.com/anaplaninc/anaplaninc.github.io/mvn-repo-ac/com/anaplan/client/anaplan-connect/1.3.6/anaplan-connect-1.3.6.jar

**Comment by nraghun** [comment]
Thanks... I will ask my Build team to help with that... 
I will update this issue after that...

**Comment by nraghun** [comment]
We were able to fix this issue by uploading the jar in our internal repository. Then the application was able to download the jar from that location and build sucessfully.

Thank you very much for your help @shuvozula

**Comment by shuvozula** [comment]
My pleasure. Glad u guys figured it out
